str = "sumit singh"
print(str[5:len(str)])
print(str[5:9])
print(str[5:])
print(str[:5])
print(str[:])

print(str[-1])
print(str[-5:-1])
print(str[-5:])

str = "my name is sumit singh"
print(str.endswith("singh"))
print(str.startswith("app"))
print(str.find("sumit"))
print(str.find("hello"))
print(str.count("i"))
print(str.upper())
print(str.lower())
print(str.capitalize())
print(str.replace("sumit", "Anshu"))
print(str.split(" "))
print(str.split("i"))
print("   hello    ".strip())
print("   hello    ".lstrip())
print("   hello    ".rstrip())
print("hello" in str)
print("hello" not in str)
print(len(str))
print(min(str))
print(max(str))
